Added gowin monitoring.

diff --git a/.github/workflows/monitor-apio-latest.yaml b/.github/workflows/monitor-apio-latest.yaml
--- a/.github/workflows/monitor-apio-latest.yaml
+++ b/.github/workflows/monitor-apio-latest.yaml
@@ -56,7 +56,7 @@ jobs:
               run: |
                 apio info system
 
-            - name: Test ice40 project
+            - name: Test ICE40 project
               run: |
                 # Exit on any error
                 set -e
@@ -110,5 +110,30 @@ jobs:
                 ls -al hardware.svg
                 ls -al ledon_tb.vcd
 
-                
+            - name: Test GOWIN project
+              run: |
+                # Exit on any error
+                set -e
+
+                # Create a project
+                mkdir gowin_project
+                cd gowin_project
+                apio examples fetch sipeed-tang-nano-9k/blinky
+                ls -al
+
+                # Run a few command
+                apio lint
+                apio build
+                apio test
+                apio graph
+                apio format
+                apio devices usb
+                apio devices serial
+
+                # Check that a few files exists (fails if not)
+                cd _build/default
+                ls -al hardware.fs
+                ls -al hardware.pnr
+                ls -al hardware.svg
+                ls -al blinky_tb.vcd
 
